import { afterEach, describe, expect, it, vi } from "vitest";
import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createSogniProductionProvider, createSogniSdkTransport, readInstalledSogniProofMetadata, resolveSogniAppIdForRole, SOGNI_PACKAGE_FILES, type SogniFactoryOptions, type SogniProviderTransport } from "./sogni-provider";
import type { SubmissionProofResolver } from "./proof-port";
import type { ProviderMediaResult } from "../../repositories/production/ports";
import { createCapabilitiesHandler, createQuoteHandler } from "./http-routes";
import type { Project } from "../../production/contracts";
import { withProductionStore } from "../../production/runtime";
import { canSatisfy } from "./capabilities";
import { hashCanonicalJson } from "../../production/hash";

const modelId="minimax-h3-fl2va-fp8_i2v";
const tempDirs:string[]=[];const priorDataDir=process.env.PERABYTE_STUDIO_DATA_DIR;afterEach(()=>{for(const dir of tempDirs.splice(0))rmSync(dir,{recursive:true,force:true});if(priorDataDir===undefined)delete process.env.PERABYTE_STUDIO_DATA_DIR;else process.env.PERABYTE_STUDIO_DATA_DIR=priorDataDir;});
const model={id:modelId,media:"video",workflowType:"i2v",assets:{referenceImage:"optional",referenceImageEnd:"optional"},maxReferenceImages:2,aspectRatios:["16:9"],minFrames:124,maxFrames:362,frameStep:17};
const project=(id="p"):Project=>({version:1,id,name:"Route test",profileId:"storybook-short-v1",profile:{id:"storybook-short-v1",format:"9:16",language:"en",ageIntent:"5-8",targetFrames:1152,projectCapMinor:null,dailyCapMinor:null},activeCanonRevisionIds:[],activeStoryRevisionId:null,activeShotPlanRevisionId:null,activeAnimaticRevisionId:null,activeAudioMixRevisionId:null,takeSelectionVersion:0,audioMixVersion:0,createdAt:1000,updatedAt:1000,saveVersion:1});
function transport(overrides:Partial<SogniProviderTransport>={}):SogniProviderTransport{return{sdkVersion:"5.49.0",configured:true,discover:vi.fn(async()=>[model]),submit:vi.fn(async()=>({providerRef:"remote-1"})),poll:vi.fn(async():Promise<ProviderMediaResult>=>({providerRef:"remote-1",state:"running",temporaryUrl:null,mime:null,width:null,height:null,frames:null,errorCode:null,errorMessage:null})),cancel:vi.fn(async()=>{}),close:vi.fn(async()=>{}),...overrides};}
function proofClient(options:{wallet?:unknown;subscription?:unknown;meFailure?:boolean;statusFailure?:boolean}={}){return{projects:{getAvailableModels:vi.fn(async()=>[model]),getVideoAssetConfig:vi.fn(async()=>({workflowType:"i2v",assets:model.assets})),create:vi.fn(async()=>({id:"proof-job"})),getStatus:vi.fn(async()=>({status:"active"})),get:vi.fn(async()=>({})),cancel:vi.fn(async()=>{})},account:{me:vi.fn(async()=>{if(options.meFailure)throw new Error("private SDK failure");return options.wallet??{walletAddress:"0xAbCdEf0123456789AbCdEf0123456789AbCdEf01",email:"private@example.test",extra:"must-not-escape"};}),getSubscriptionStatus:vi.fn(async()=>{if(options.statusFailure)throw new Error("status unavailable with credential text");return options.subscription??{active:true,status:"future_provider_state",tier:"future_tier",currentPeriodEnd:"2030-01-02T03:04:05.1Z",providerVersion:7,email:"private@example.test",walletAddress:"must-not-escape"};})},dispose:vi.fn()};}

describe("Sogni production provider composition",()=>{
  it("I01-C13-A anchors the installed proof metadata on the process working directory (bundler-safe, stable across calls)",()=>{
    const fixtureRoot=mkdtempSync(join(tmpdir(),"sogni-proof-cwd-"));tempDirs.push(fixtureRoot);
    const fixturePackageRoot=join(fixtureRoot,"node_modules","@sogni-ai","sogni-client");
    for(const directory of new Set(SOGNI_PACKAGE_FILES.map((file)=>dirname(file))))mkdirSync(join(fixturePackageRoot,directory),{recursive:true});
    for(const file of SOGNI_PACKAGE_FILES)writeFileSync(join(fixturePackageRoot,file),`c13-fixture:${file}`);
    const fixturePackageJson=JSON.stringify({name:"@sogni-ai/sogni-client",version:"9.9.9"});
    writeFileSync(join(fixturePackageRoot,"package.json"),fixturePackageJson);
    const fixtureFiles=SOGNI_PACKAGE_FILES.map(path=>({path,sha256:createHash("sha256").update(path==="package.json"?fixturePackageJson:`c13-fixture:${path}`).digest("hex")})).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);
    const fixtureHash=hashCanonicalJson({schemaVersion:1,packageName:"@sogni-ai/sogni-client",sdkVersion:"9.9.9",files:fixtureFiles});
    const priorCwd=process.cwd();
    try{
      process.chdir(fixtureRoot);
      const first=readInstalledSogniProofMetadata(),second=readInstalledSogniProofMetadata();
      expect(second).toEqual(first);
      expect(first).toMatchObject({sdkVersion:"9.9.9",sdkSourceHash:fixtureHash,adapterVersion:"sogni-production-proof-v1"});
    }finally{process.chdir(priorCwd);}
    const installed=readInstalledSogniProofMetadata();
    expect(installed).toMatchObject({sdkVersion:"5.49.0",adapterVersion:"sogni-production-proof-v1"});
    expect(readInstalledSogniProofMetadata()).toEqual(installed);
  });
  it("I01-B6-P observes bounded account facts from the actual cached SDK client",async()=>{
    const metadata=readInstalledSogniProofMetadata();expect(metadata).toMatchObject({sdkVersion:"5.49.0",sdkSourceHash:"5c8d291a5fa677190e7853c7983d77109e3a86299aa8fcd0d3e4fc55af47b983",adapterVersion:"sogni-production-proof-v1"});
    const dir=mkdtempSync(join(tmpdir(),"sogni-proof-observation-"));tempDirs.push(dir);const env={SOGNI_API_KEY:"  fixture-key-only  "},address="0xAbCdEf0123456789AbCdEf0123456789AbCdEf01",client=proofClient();
    const createInstance=vi.fn(async(config:Record<string,unknown>)=>{expect(config.apiKey).toBe("fixture-key-only");return client;});
    const web=createSogniProductionProvider({env,dataDir:dir,role:"web",proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance}})});
    const webObservation=await web.observeAccount();expect(createInstance).toHaveBeenCalledTimes(1);expect(client.account.me).toHaveBeenCalledTimes(1);expect(client.account.getSubscriptionStatus).toHaveBeenCalledTimes(1);
    expect(webObservation).toMatchObject({providerId:"sogni",captured:{session:{role:"web",sdkVersion:metadata.sdkVersion,sdkSourceHash:metadata.sdkSourceHash,adapterVersion:metadata.adapterVersion},credentialFingerprint:createHash("sha256").update("fixture-key-only").digest("hex")},subscription:{active:true,status:"future_provider_state",tier:"future_tier",providerVersion:7}});
    expect(webObservation.captured.accountId).toBe(`sogni-account:${hashCanonicalJson({schemaVersion:1,providerId:"sogni",walletAddress:address.toLowerCase()})}`);
    expect(webObservation.subscription?.currentPeriodEnd).toBe(Date.parse("2030-01-02T03:04:05.100Z"));expect(Object.isFrozen(webObservation)).toBe(true);expect(Object.isFrozen(webObservation.captured.session)).toBe(true);
    expect(JSON.stringify(webObservation)).not.toMatch(/private@example\.test|must-not-escape|fixture-key-only|0xAbCdEf/i);
    const workerClient=proofClient(),worker=createSogniProductionProvider({env,dataDir:dir,role:"worker",proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async(config:Record<string,unknown>)=>{expect(config.apiKey).toBe("fixture-key-only");return workerClient;}}})});
    const workerObservation=await worker.observeAccount();expect(workerObservation.captured.accountId).toBe(webObservation.captured.accountId);expect(workerObservation.captured.credentialFingerprint).toBe(webObservation.captured.credentialFingerprint);expect(workerObservation.captured.session.sessionId).not.toBe(webObservation.captured.session.sessionId);expect(workerObservation.captured.session.role).toBe("worker");expect(await resolveSogniAppIdForRole(dir,"web")).not.toBe(await resolveSogniAppIdForRole(dir,"worker"));
    await web.close();expect(web.currentSession()).toBeNull();const replacement=proofClient(),recreated=createSogniProductionProvider({env,dataDir:dir,role:"web",proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>replacement}})});
    const replacementObservation=await recreated.observeAccount();expect(replacementObservation.captured.session.sessionId).not.toBe(webObservation.captured.session.sessionId);
    const unavailable=proofClient({statusFailure:true}),offline=createSogniProductionProvider({env,dataDir:join(dir,"offline"),proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>unavailable}})});expect((await offline.observeAccount()).subscription).toBeNull();
    const malformed=proofClient({subscription:{active:true,status:"",tier:{private:true}}}),malformedProvider=createSogniProductionProvider({env,dataDir:join(dir,"malformed"),proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>malformed}})});expect((await malformedProvider.observeAccount()).subscription).toBeNull();
    const missingImport=vi.fn(),missing=createSogniProductionProvider({env,dataDir:join(dir,"missing"),importSdk:missingImport});await expect(missing.observeAccount()).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(missingImport).not.toHaveBeenCalled();
    const badMe=proofClient({wallet:{walletAddress:"not-an-address"}}),badProvider=createSogniProductionProvider({env,dataDir:join(dir,"bad-me"),proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>badMe}})});await expect(badProvider.observeAccount()).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(badProvider.currentSession()).toBeNull();
    await Promise.all([worker.close(),recreated.close(),offline.close(),malformedProvider.close(),badProvider.close()]);
  });
  it("I01-B6-P runs the synchronous proof guard after asset awaits immediately before SDK create",async()=>{
    const metadata=readInstalledSogniProofMetadata(),dir=mkdtempSync(join(tmpdir(),"sogni-proof-submit-"));tempDirs.push(dir);const env={SOGNI_API_KEY:"fixture-submit-key"};
    const createGuarded=(options:{resolver?:SubmissionProofResolver;readAsset?:(id:string)=>Promise<Buffer>;createInstance?:(config:Record<string,unknown>)=>Promise<ReturnType<typeof proofClient>>;now?:()=>number}={})=>{
      const client=options.createInstance?undefined:proofClient();const provider=createSogniProductionProvider({env,dataDir:join(dir,randomUUID()),role:"worker",proofMetadata:metadata,submissionProofResolver:options.resolver,readAsset:options.readAsset??(async()=>Buffer.from("offline-frame")),now:options.now,importSdk:async()=>({SogniClient:{createInstance:options.createInstance??(async()=>client!)}})});return{provider,client};
    };
    const makeRequest=()=>({projectId:"p",jobId:"j",idempotencyKey:"i",quoteId:"q",billingMode:"tokens" as const,providerId:"sogni",modelId,prompt:"move",inputs:[{assetId:"start",role:"start_frame" as const,required:true}],parameters:{frameCount:124,aspect:"16:9"}});
    const events:string[]=[],client=proofClient(),resolver=vi.fn(((snapshot,captured,at)=>{events.push("guard");expect(snapshot.jobId).toBe("j");expect(captured.accountId).toContain("sogni-account:");expect(captured.credentialFingerprint).toBe(createHash("sha256").update(env.SOGNI_API_KEY).digest("hex"));expect(captured.session.sdkVersion).toBe(metadata.sdkVersion);expect(captured.session.sdkSourceHash).toBe(metadata.sdkSourceHash);expect(captured.session.adapterVersion).toBe(metadata.adapterVersion);expect(at).toBe(5_000);return true;}) satisfies SubmissionProofResolver);
    const guarded=createGuarded({resolver,now:()=>5_000,createInstance:async()=>client,readAsset:async()=>{events.push("asset");return Buffer.from("offline-frame");}}),capability=await guarded.provider.discoverCapabilities(modelId);await guarded.provider.observeAccount();
    client.projects.create.mockImplementation(async()=>{events.push("create");return{id:"proof-job"};});const ack=await guarded.provider.submit(makeRequest(),capability);expect(ack.providerRef).toBe("proof-job");expect(events).toEqual(["asset","guard","create"]);expect(resolver).toHaveBeenCalledTimes(1);expect(client.projects.create).toHaveBeenCalledTimes(1);await guarded.provider.close();
    const denyClient=proofClient(),deny=createGuarded({resolver:()=>false,createInstance:async()=>denyClient});const denyCapability=await deny.provider.discoverCapabilities(modelId);await deny.provider.observeAccount();await expect(deny.provider.submit(makeRequest(),denyCapability)).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(denyClient.projects.create).not.toHaveBeenCalled();await deny.provider.close();
    const asyncClient=proofClient(),asyncResolver=((()=>Promise.resolve(true)) as unknown as SubmissionProofResolver),asyncGuard=createGuarded({resolver:asyncResolver,createInstance:async()=>asyncClient});const asyncCapability=await asyncGuard.provider.discoverCapabilities(modelId);await asyncGuard.provider.observeAccount();await expect(asyncGuard.provider.submit(makeRequest(),asyncCapability)).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(asyncClient.projects.create).not.toHaveBeenCalled();await asyncGuard.provider.close();
    const closedClient=proofClient();let releaseAsset!:(bytes:Buffer)=>void;const deferred=new Promise<Buffer>(resolve=>{releaseAsset=resolve;}),closeGuard=createGuarded({resolver:()=>true,createInstance:async()=>closedClient,readAsset:()=>deferred}),closeCapability=await closeGuard.provider.discoverCapabilities(modelId);await closeGuard.provider.observeAccount();const pending=closeGuard.provider.submit(makeRequest(),closeCapability);await Promise.resolve();await closeGuard.provider.close();releaseAsset(Buffer.from("offline-frame"));await expect(pending).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(closedClient.projects.create).not.toHaveBeenCalled();
    const noResolverClient=proofClient(),noResolver=createGuarded({createInstance:async()=>noResolverClient}),noResolverCapability=await noResolver.provider.discoverCapabilities(modelId);await noResolver.provider.observeAccount();await expect(noResolver.provider.submit(makeRequest(),noResolverCapability)).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(noResolverClient.projects.create).not.toHaveBeenCalled();await noResolver.provider.close();
  });
  it("uses installed SDK transport behind injection, maps required H3 roles, and records one submit",async()=>{const sdk=transport();const provider=createSogniProductionProvider({transport:sdk,readAsset:async()=>Buffer.from("asset")});const capability=await provider.discoverCapabilities(modelId);const ack=await provider.submit({projectId:"p",jobId:"j",idempotencyKey:"i",quoteId:"q",billingMode:"tokens",providerId:"sogni",modelId,prompt:"move",inputs:[{assetId:"start",role:"start_frame",required:true},{assetId:"end",role:"end_frame",required:true}],parameters:{frameCount:124,aspect:"16:9",seed:4}},capability);expect(sdk.submit).toHaveBeenCalledTimes(1);expect(ack.providerRef).toBe("remote-1");expect(ack.honoredInputs.inputs.map(x=>x.state)).toEqual(["acknowledged","acknowledged"]);expect(ack.honoredInputs.inputs.map(x=>x.providerField)).toEqual(["referenceImage","referenceImageEnd"]);});
  it("keeps distinct endpoint roles when one immutable asset supplies both endpoints",async()=>{const sdk=transport();const provider=createSogniProductionProvider({transport:sdk,readAsset:async()=>Buffer.from("same frame")});const capability=await provider.discoverCapabilities(modelId);await provider.submit({projectId:"p",jobId:"j",idempotencyKey:"i",quoteId:"q",billingMode:"tokens",providerId:"sogni",modelId,prompt:"move",inputs:[{assetId:"same",role:"start_frame",required:true},{assetId:"same",role:"end_frame",required:true}],parameters:{frameCount:124,aspect:"16:9"}},capability);const submission=(sdk.submit as ReturnType<typeof vi.fn>).mock.calls[0]![0];expect(submission.parameters.referenceImage).toEqual(Buffer.from("same frame"));expect(submission.parameters.referenceImageEnd).toEqual(Buffer.from("same frame"));});
  it("rejects a required role before transport when H3 capabilities do not support it",async()=>{const sdk=transport({discover:vi.fn(async()=>[{...model,assets:{referenceImage:"forbidden",referenceImageEnd:"forbidden"}}])});const provider=createSogniProductionProvider({transport:sdk,readAsset:async()=>Buffer.from("asset")});const capability=await provider.discoverCapabilities(modelId);await expect(provider.submit({projectId:"p",jobId:"j",idempotencyKey:"i",quoteId:"q",billingMode:"tokens",providerId:"sogni",modelId,prompt:"move",inputs:[{assetId:"start",role:"start_frame",required:true}],parameters:{frameCount:124}},capability)).rejects.toThrow(/required|support|reference/i);expect(sdk.submit).not.toHaveBeenCalled();});
  it("leaves prices and entitlement unknown without a verified account quote",async()=>{const provider=createSogniProductionProvider({transport:transport()});const result=await provider.quote({projectId:"p",providerId:"sogni",modelId,operation:"take",inputSnapshot:{revisionIds:[],assetIds:[],parameters:{}}});expect(result).toMatchObject({entitlement:"unknown",estimateMinMinor:null,estimateMaxMinor:null,withinAuthorizedCap:"unknown"});});
  it("keeps role app IDs stable and distinct for web and worker",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-appids-"));tempDirs.push(dir);const worker=await resolveSogniAppIdForRole(dir,"worker");const web=await resolveSogniAppIdForRole(dir,"web");expect(await resolveSogniAppIdForRole(dir,"worker")).toBe(worker);expect(await resolveSogniAppIdForRole(dir,"web")).toBe(web);expect(worker).not.toBe(web);});
  it("does not import or connect the real SDK when configuration is missing",async()=>{const importSdk=vi.fn();const sdk=createSogniSdkTransport({env:{},dataDir:"/tmp/perabyte-no-credentials",importSdk});await expect(sdk.discover([])).rejects.toThrow(/SOGNI_API_KEY/i);expect(importSdk).not.toHaveBeenCalled();});
  it("maps installed SDK completed media and terminal status shapes through the injected transport",async()=>{const mediaDownloadUrl=vi.fn(async()=>"https://signed.example/output.mp4");let status="completed";const client={projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status})),get:vi.fn(async()=>({completedWorkerJobs:[{id:"job",imgID:"asset",status:"jobCompleted",outputFormat:"mp4"}]})),mediaDownloadUrl,downloadUrl:vi.fn(async()=>"https://signed.example/output.png"),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-fake-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});expect(await sdk.poll("project")).toMatchObject({state:"completed",mime:"video/mp4",temporaryUrl:"https://signed.example/output.mp4"});expect(mediaDownloadUrl).toHaveBeenCalledTimes(1);status="errored";expect(await sdk.poll("project")).toMatchObject({state:"failed",errorCode:"MEDIA_UNAVAILABLE"});await sdk.close();});
  it("recovers the completed SDK 5.49 job id and nested format without downloading an unfinished job",async()=>{const mediaDownloadUrl=vi.fn(async({id}:{id:string})=>`https://signed.example/${id}.mov`);const getStatus=vi.fn(async(id:string)=>({status:id==="known-project"?"completed":"completed"}));const get=vi.fn(async(id:string)=>({completedWorkerJobs:[],workerJobs:[{id:"unfinished-id",imgID:"unfinished-asset",status:"jobProgress",result:{outputFormat:"mp4"}},{id:"recovered-complete-id",status:"jobCompleted",result:{outputFormat:"mov"}}]}));const client={projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"project"})),getStatus,get,mediaDownloadUrl,downloadUrl:vi.fn(async()=>"https://signed.example/wrong.png"),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-recovered-result-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).resolves.toMatchObject({providerRef:"known-project",state:"completed",mime:"video/quicktime",temporaryUrl:"https://signed.example/recovered-complete-id.mov"});expect(getStatus).toHaveBeenCalledExactlyOnceWith("known-project");expect(get).toHaveBeenCalledExactlyOnceWith("known-project");expect(mediaDownloadUrl).toHaveBeenCalledExactlyOnceWith({jobId:"known-project",id:"recovered-complete-id",type:"complete"});expect(client.projects.downloadUrl).not.toHaveBeenCalled();await sdk.close();});
  it("rejects unknown completed output formats without claiming an image MIME or downloading",async()=>{const downloadUrl=vi.fn(async()=>"https://signed.example/unknown.bin");const getAvailableModels=vi.fn(async()=>[{id:"known-image-model",media:"image"}]);const client={projects:{getAvailableModels,create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({model:{id:"known-image-model"},completedWorkerJobs:[{id:"unknown-format-id",status:"jobCompleted",result:{outputFormat:"avif"}}]})),mediaDownloadUrl:vi.fn(async()=>"https://signed.example/unknown.bin"),downloadUrl,cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-unknown-format-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).rejects.toThrow(/no supported media format/i);expect(downloadUrl).not.toHaveBeenCalled();expect(client.projects.mediaDownloadUrl).not.toHaveBeenCalled();expect(getAvailableModels).not.toHaveBeenCalled();await sdk.close();});
  it.each([{format:"png",mime:"image/png"},{format:"jpg",mime:"image/jpeg"},{format:"jpeg",mime:"image/jpeg"},{format:"webp",mime:"image/webp"}])("passes the exact $mime content type when downloading $format image results",async({format,mime})=>{const downloadUrl=vi.fn(async({contentType}:{contentType?:string})=>contentType===mime?`https://signed.example/output.${format}`:"https://signed.example/default.png");const client={projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({completedWorkerJobs:[{id:"image-result-id",status:"jobCompleted",result:{outputFormat:format}}]})),mediaDownloadUrl:vi.fn(async()=>"https://signed.example/wrong.mp4"),downloadUrl,cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),`sogni-${format}-content-type-`));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).resolves.toMatchObject({state:"completed",mime,temporaryUrl:`https://signed.example/output.${format}`});expect(downloadUrl).toHaveBeenCalledExactlyOnceWith({jobId:"known-project",imageId:"image-result-id",type:"complete",contentType:mime});expect(client.projects.mediaDownloadUrl).not.toHaveBeenCalled();await sdk.close();});
  it("recovers missing image format as PNG only when exact live model evidence identifies an image model",async()=>{const getAvailableModels=vi.fn(async()=>[{id:"known-image-model",media:"image"}]);const downloadUrl=vi.fn(async({contentType}:{contentType?:string})=>contentType==="image/png"?"https://signed.example/default.png":"https://signed.example/wrong" );const client={projects:{getAvailableModels,create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({model:{id:"known-image-model"},completedWorkerJobs:[{id:"historical-image-id",status:"jobCompleted"}]})),mediaDownloadUrl:vi.fn(async()=>"https://signed.example/wrong.mp4"),downloadUrl,cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-missing-image-format-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).resolves.toMatchObject({state:"completed",mime:"image/png",temporaryUrl:"https://signed.example/default.png"});expect(getAvailableModels).toHaveBeenCalledExactlyOnceWith("fast");expect(downloadUrl).toHaveBeenCalledExactlyOnceWith({jobId:"known-project",imageId:"historical-image-id",type:"complete",contentType:"image/png"});await sdk.close();});
  it("C13-LIVE-FIX-4 recovers a completed H3 video take whose worker job reports no outputFormat as video/mp4 from the discovered video model",async()=>{const getAvailableModels=vi.fn(async()=>[{id:"minimax-h3-video-model",media:"video"}]);const mediaDownloadUrl=vi.fn(async({id}:{id:string})=>`https://signed.example/${id}.mp4`);const client={projects:{getAvailableModels,create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({model:{id:"minimax-h3-video-model"},completedWorkerJobs:[{id:"h3-job-id",imgID:"h3-img-id",status:"jobCompleted"}]})),mediaDownloadUrl,downloadUrl:vi.fn(async()=>"https://signed.example/wrong.png"),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-missing-video-format-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).resolves.toMatchObject({state:"completed",mime:"video/mp4",temporaryUrl:"https://signed.example/h3-img-id.mp4"});expect(getAvailableModels).toHaveBeenCalledExactlyOnceWith("fast");expect(mediaDownloadUrl).toHaveBeenCalledExactlyOnceWith({jobId:"known-project",id:"h3-img-id",type:"complete"});expect(client.projects.downloadUrl).not.toHaveBeenCalled();await sdk.close();});
  it("blocks missing image formats when the project's model has no exact affirmative image catalog match",async()=>{const getAvailableModels=vi.fn(async()=>[{id:"different-model",media:"image"}]);const downloadUrl=vi.fn(async()=>"https://signed.example/wrong.png");const client={projects:{getAvailableModels,create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({model:{id:"unknown-model"},completedWorkerJobs:[{id:"historical-result-id",status:"jobCompleted"}]})),mediaDownloadUrl:vi.fn(async()=>"https://signed.example/wrong.mp4"),downloadUrl,cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-unknown-image-model-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).rejects.toThrow(/no supported media format/i);expect(getAvailableModels).toHaveBeenCalledExactlyOnceWith("fast");expect(downloadUrl).not.toHaveBeenCalled();await sdk.close();});
  it("refuses completed projects that have no completed media instead of downloading a running worker job",async()=>{const mediaDownloadUrl=vi.fn(async()=>"https://signed.example/unfinished.mp4");const client={projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"completed"})),get:vi.fn(async()=>({completedWorkerJobs:[],workerJobs:[{id:"running-id",imgID:"running-asset",status:"jobProgress",result:{outputFormat:"mp4"}}]})),mediaDownloadUrl,downloadUrl:vi.fn(async()=>"https://signed.example/running.png"),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const dir=mkdtempSync(join(tmpdir(),"sogni-no-completed-result-"));tempDirs.push(dir);const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(sdk.poll("known-project")).rejects.toThrow(/completed project has no result asset reference/i);expect(mediaDownloadUrl).not.toHaveBeenCalled();expect(client.projects.downloadUrl).not.toHaveBeenCalled();await sdk.close();});
  it("derives H3 limits only from exact live model availability and matching installed SDK workflow config",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-discovery-"));tempDirs.push(dir);const client={projects:{getAvailableModels:vi.fn(async()=>[{id:modelId,name:"H3",workerCount:2,media:"video"}]),getVideoAssetConfig:vi.fn(async()=>({workflowType:"i2v",assets:{referenceImage:"required",referenceImageEnd:"optional"}})),getModelOptions:vi.fn(async()=>({type:"video",width:{min:256,max:1920,step:8},height:{min:256,max:1920,step:8},fps:{values:[24]},sampler:{values:["euler"]},scheduler:{values:["normal"]}}))},dispose:vi.fn()};const provider=createSogniProductionProvider({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"probe",now:Date.now,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});const capability=await provider.discoverCapabilities(modelId);expect(client.projects.getAvailableModels).toHaveBeenCalledWith("fast");expect(client.projects.getVideoAssetConfig).toHaveBeenCalledWith(modelId);expect(capability).toMatchObject({provenance:"live_catalog",supportedOperations:["video"],supportsStartFrame:true,supportsEndFrame:true,minFrames:124,maxFrames:362,frameStep:17,maxReferenceImages:2});expect(canSatisfy(capability,{startFrame:true},Date.now())).toBe(true);expect(capability).not.toHaveProperty("resolution");await provider.close();});
  it("composes capabilities and quotes HTTP handlers with an injected installed-SDK-shaped client and no real network",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-route-composition-"));tempDirs.push(dir);process.env.PERABYTE_STUDIO_DATA_DIR=dir;await withProductionStore(store=>store.transaction(tx=>tx.insertProject(project())));const client={projects:{getAvailableModels:vi.fn(async()=>[{id:modelId,name:"H3",workerCount:2,media:"video"}]),getVideoAssetConfig:vi.fn(async()=>({workflowType:"i2v",assets:{referenceImage:"required",referenceImageEnd:"optional"}})),getModelOptions:vi.fn(async()=>({type:"video",fps:{values:[24]}})),create:vi.fn(async()=>({id:"project"})),getStatus:vi.fn(async()=>({status:"active"})),get:vi.fn(async()=>({})),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const createProvider=(options:SogniFactoryOptions)=>createSogniProductionProvider({...options,env:{SOGNI_API_KEY:"fake-fixture-only"},dataDir:dir,now:Date.now,importSdk:async()=>({SogniClient:{createInstance:async(config:Record<string,unknown>)=>{expect(config.apiKey).toBe("fake-fixture-only");return client;}}})});const capabilities=createCapabilitiesHandler(createProvider);const capabilityResponse=await capabilities(new Request(`http://localhost/api/production/capabilities?providerModelIds=${encodeURIComponent(modelId)}`));expect(capabilityResponse.status,await capabilityResponse.clone().text()).toBe(200);expect(await capabilityResponse.json()).toMatchObject({receipts:[{modelId,provenance:"live_catalog",supportsStartFrame:true,minFrames:124,maxFrames:362}]});expect(client.projects.getAvailableModels).toHaveBeenCalledWith("fast");const quotes=createQuoteHandler(createProvider);const quoteResponse=await quotes(new Request("http://localhost/api/production/quotes",{method:"POST",headers:{origin:"http://localhost","content-type":"application/json"},body:JSON.stringify({projectId:"p",providerId:"sogni",modelId,operation:"take",inputSnapshot:{revisionIds:[],assetIds:[],parameters:{frameCount:124}}})}));expect(quoteResponse.status,await quoteResponse.clone().text()).toBe(200);expect(await quoteResponse.json()).toMatchObject({providerId:"sogni",modelId,entitlement:"unknown",estimateMinMinor:null,estimateMaxMinor:null,withinAuthorizedCap:"unknown"});expect(client.projects.create).not.toHaveBeenCalled();expect(client.projects.getModelOptions).not.toHaveBeenCalled();expect(client.dispose).toHaveBeenCalledTimes(1);});
  it("returns client-safe route errors for duplicate capability IDs, unknown projects, and expired quote evidence",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-route-errors-"));tempDirs.push(dir);process.env.PERABYTE_STUDIO_DATA_DIR=dir;await withProductionStore(store=>store.transaction(tx=>tx.insertProject(project())));const providerFactory=vi.fn((options:SogniFactoryOptions)=>createSogniProductionProvider({...options,env:{},dataDir:dir,now:()=>0}));const capabilities=createCapabilitiesHandler(providerFactory);const repeated=await capabilities(new Request(`http://localhost/api/production/capabilities?providerModelIds=${modelId}&providerModelIds=${modelId}`));expect(repeated.status).toBe(400);expect(providerFactory).not.toHaveBeenCalled();const quotes=createQuoteHandler(providerFactory);const command={providerId:"sogni",modelId,operation:"take",inputSnapshot:{revisionIds:[],assetIds:[],parameters:{frameCount:124}}};const unknown=await quotes(new Request("http://localhost/api/production/quotes",{method:"POST",headers:{origin:"http://localhost","content-type":"application/json"},body:JSON.stringify({...command,projectId:"missing"})}));expect(unknown.status).toBe(404);expect(providerFactory).not.toHaveBeenCalled();const expired=await quotes(new Request("http://localhost/api/production/quotes",{method:"POST",headers:{origin:"http://localhost","content-type":"application/json"},body:JSON.stringify({...command,projectId:"p"})}));expect(expired.status).toBe(400);expect(providerFactory).toHaveBeenCalledTimes(1);});
  it("releases exclusive worker ownership on close and reclaims a stale PID lock after process death",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-worker-lock-"));tempDirs.push(dir);const makeClient=()=>({projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"job"})),getStatus:vi.fn(async()=>({status:"active"})),get:vi.fn(async()=>({})),cancel:vi.fn(async()=>{})},dispose:vi.fn()});const firstClient=makeClient();const secondClient=makeClient();const config={env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"worker" as const};const first=createSogniSdkTransport({...config,importSdk:async()=>({SogniClient:{createInstance:async()=>firstClient}})});const second=createSogniSdkTransport({...config,importSdk:async()=>({SogniClient:{createInstance:async()=>secondClient}})});await first.discover([]);await expect(second.discover([])).rejects.toThrow(/another local worker/i);await first.close();writeFileSync(join(dir,"sogni-worker-owner.lock"),"2147483647");await expect(second.discover([])).resolves.toEqual([]);await second.close();});
  it("releases worker ownership after SDK initialization fails so startup can retry",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-worker-init-retry-"));tempDirs.push(dir);let creations=0;const client={projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"job"})),getStatus:vi.fn(async()=>({status:"active"})),get:vi.fn(async()=>({})),cancel:vi.fn(async()=>{})},dispose:vi.fn()};const sdk=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"worker",importSdk:async()=>({SogniClient:{createInstance:async()=>{creations++;if(creations===1)throw new Error("SDK init failed");return client;}}})});await expect(sdk.discover([])).rejects.toThrow(/SDK init failed/);await expect(sdk.discover([])).resolves.toEqual([]);expect(creations).toBe(2);await sdk.close();});
  it("I01-B6-W-LOCK stale init attempt after close never orphans the worker lock",async()=>{const dir=mkdtempSync(join(tmpdir(),"sogni-stale-init-lock-"));tempDirs.push(dir);const makeClient=()=>({projects:{getAvailableModels:vi.fn(async()=>[]),create:vi.fn(async()=>({id:"job"})),getStatus:vi.fn(async()=>({status:"active"})),get:vi.fn(async()=>({})),cancel:vi.fn(async()=>{})},dispose:vi.fn()});const config={env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"worker" as const};let releaseGate!:(value:void)=>void;let gate:Promise<void>=new Promise<void>(resolve=>{releaseGate=resolve;});const first=createSogniSdkTransport({...config,importSdk:async()=>{await gate;return{SogniClient:{createInstance:async()=>makeClient()}};}});const stale=first.discover([]);const closing=first.close();releaseGate();await expect(stale).rejects.toMatchObject({code:"BUDGET_BLOCKED"});const second=createSogniSdkTransport({...config,importSdk:async()=>({SogniClient:{createInstance:async()=>makeClient()}})});await expect(second.discover([])).resolves.toEqual([]);await closing;await second.close();gate=new Promise<void>(resolve=>{releaseGate=resolve;});const reinit=first.discover([]);const closingDuringReinit=first.close();releaseGate();await expect(reinit).rejects.toMatchObject({code:"BUDGET_BLOCKED"});const third=createSogniSdkTransport({...config,importSdk:async()=>({SogniClient:{createInstance:async()=>makeClient()}})});await expect(third.discover([])).resolves.toEqual([]);await closingDuringReinit;await third.close();});
  it("C13-LIVE-FIX-3 submits the image anchor as sizePreset custom with explicit 9:16@1080p dimensions instead of the raw resolution string",async()=>{
    const metadata=readInstalledSogniProofMetadata(),dir=mkdtempSync(join(tmpdir(),"sogni-live-fix-3-anchor-"));tempDirs.push(dir);const env={SOGNI_API_KEY:"fixture-live-fix-3"};
    const imageModel={id:"flux1-schnell-fp8",media:"image"},base=proofClient(),client={...base,projects:{...base.projects,getAvailableModels:vi.fn(async():Promise<Array<Record<string,unknown>>>=>[imageModel])}};
    const provider=createSogniProductionProvider({env,dataDir:join(dir,randomUUID()),role:"worker",proofMetadata:metadata,submissionProofResolver:()=>true,readAsset:async()=>Buffer.from("frame"),importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});
    await provider.observeAccount();const capability=await provider.discoverCapabilities(imageModel.id);
    await provider.submit({projectId:"p",jobId:"anchor-j",idempotencyKey:"i1",quoteId:"q1",billingMode:"tokens",providerId:"sogni",modelId:imageModel.id,prompt:"anchor",inputs:[],parameters:{aspect:"9:16",resolution:"1080p"}},capability);
    expect(client.projects.create).toHaveBeenCalledTimes(1);const parameters=(client.projects.create as ReturnType<typeof vi.fn>).mock.calls[0]![0] as Record<string,unknown>;
    expect(parameters).toMatchObject({type:"image",modelId:imageModel.id,sizePreset:"custom",width:720,height:1280});expect(parameters.sizePreset).not.toBe("1080p");
    await provider.close();
  });
  it("C13-LIVE-FIX-3 adds explicit 32-grid dimensions to the H3 take so 9:16@1080p renders on the requested grid",async()=>{
    const metadata=readInstalledSogniProofMetadata(),dir=mkdtempSync(join(tmpdir(),"sogni-live-fix-3-take-"));tempDirs.push(dir);const env={SOGNI_API_KEY:"fixture-live-fix-3"};
    const h3Model={id:"minimax-h3-fl2va-fp8_i2v_turbo",media:"video",workflowType:"i2v",assets:{referenceImage:"optional",referenceImageEnd:"optional"}},base=proofClient(),client={...base,projects:{...base.projects,getAvailableModels:vi.fn(async():Promise<Array<Record<string,unknown>>>=>[h3Model]),getVideoAssetConfig:vi.fn(async():Promise<{workflowType:string|null;assets?:Record<string,string>|null}>=>({workflowType:"i2v",assets:h3Model.assets}))}};
    const provider=createSogniProductionProvider({env,dataDir:join(dir,randomUUID()),role:"worker",proofMetadata:metadata,submissionProofResolver:()=>true,readAsset:async()=>Buffer.from("frame"),importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});
    await provider.observeAccount();const capability=await provider.discoverCapabilities(h3Model.id);
    await provider.submit({projectId:"p",jobId:"take-j",idempotencyKey:"i2",quoteId:"q2",billingMode:"tokens",providerId:"sogni",modelId:h3Model.id,prompt:"take",inputs:[{assetId:"start",role:"start_frame",required:true}],parameters:{frameCount:192,aspect:"9:16",resolution:"1080p",verifiedResolution:"1080p"}},capability);
    expect(client.projects.create).toHaveBeenCalledTimes(1);const parameters=(client.projects.create as ReturnType<typeof vi.fn>).mock.calls[0]![0] as Record<string,unknown>;
    expect(parameters).toMatchObject({type:"video",modelId:h3Model.id,ratio:"9:16",frames:192});
    expect(typeof parameters.width).toBe("number");expect(typeof parameters.height).toBe("number");expect((parameters.width as number)%32).toBe(0);expect((parameters.height as number)%32).toBe(0);
    await provider.close();
  });
  it("I01-B6-W-LOCK observeAccount me()-rejection denies and invalidates (P coverageNit)",async()=>{const metadata=readInstalledSogniProofMetadata(),dir=mkdtempSync(join(tmpdir(),"sogni-me-rejection-"));tempDirs.push(dir);const client=proofClient({meFailure:true});const first=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"worker",proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>client}})});await expect(first.observeAccount!()).rejects.toMatchObject({code:"BUDGET_BLOCKED"});expect(client.account.me).toHaveBeenCalledTimes(1);expect(first.currentSession!()).toBeNull();await first.close();const recovered=proofClient();const second=createSogniSdkTransport({env:{SOGNI_API_KEY:"test-only"},dataDir:dir,role:"worker",proofMetadata:metadata,importSdk:async()=>({SogniClient:{createInstance:async()=>recovered}})});await expect(second.observeAccount!()).resolves.toMatchObject({providerId:"sogni",captured:{session:{role:"worker"}},subscription:{active:true,status:"future_provider_state"}});expect(second.currentSession!()?.accountId).toContain("sogni-account:");await second.close();});
});
